FROM python:3.9-slim

COPY requirements.txt requirements.txt

RUN pip install --default-timeout=200 -r requirements.txt

RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6 ffmpeg

COPY . . 

CMD ["python", "app.py"]
